### ISSUE TITLE
error loading model

### ISSUE THREAD

**Issue by kingsommar** [MarsQQ/Aimmy#32] opened 2023-10-29 19:45 UTC
![awdawdaw](https://github.com/MarsQQ/Aimmy/assets/149288492/9d6b8f3c-dd4b-4036-b552-2ba3e3703581)
![dwwawadawddaw](https://github.com/MarsQQ/Aimmy/assets/149288492/fee2395d-2b34-41bf-9cfb-92ff442c1f35)
![Screenshot 2023-10-29 090820](https://github.com/MarsQQ/Aimmy/assets/149288492/4c1493eb-9e4a-4a60-95f0-89b1704355bc)
![wdad](https://github.com/MarsQQ/Aimmy/assets/149288492/87e1df8d-7e5e-42b9-bf8b-6e3a503a99ef)

**Comment by Babyhamsta** [comment] 2023-10-29 20:15
From the error message it appears the exe cannot find the onnxruntime.dll or DirectML.dll. Please ensure both dlls are in the same folder as the exe and that you've fully extracted the zip file from releases.

**Comment by kingsommar** [comment] 2023-10-29 20:56
![image](https://github.com/MarsQQ/Aimmy/assets/149288492/d25bb541-1382-4164-bfae-e15a5f9abf03)
are these the dlls because it still dosnt work and it is extracted

**Comment by kingsommar** [comment] 2023-10-29 21:00
never mind the problem fixzed you need these files 
![image](https://github.com/MarsQQ/Aimmy/assets/149288492/f3acf425-93c8-4bbf-a70e-ff666e874739)

**Comment by Catplayz2011** [comment] 2023-10-29 21:14
How did you fixed it ?

**Comment by Catplayz2011** [comment] 2023-10-29 21:16
> never mind the problem fixzed you need these files ![image](https://user-images.githubusercontent.com/149288492/278897833-f3acf425-93c8-4bbf-a70e-ff666e874739.png)


How have you fixed it ? And do i need to download all the files show on the pic ?

**Comment by kingsommar** [comment] 2023-10-29 22:07
yes download the files just earch them up

**Comment by Babyhamsta** [comment] 2023-10-30 00:30
Duplicate of https://github.com/MarsQQ/Aimmy/issues/18 - Fix was added to Setup instructions in README

**Closed by Babyhamsta** 2023-10-30 00:30 UTC
Labels: duplicate, good first issue
